### ISSUE TITLE
[Question] How to Configure redis using autofac for BasketApi

### ISSUE THREAD

**Issue by FrankDupree** [dotnet-architecture/eShopOnContainers#1045]
I'm gonna be upfront and admit i'm running the eshopcontainers using visual studio and not docker. I hit a snag trying to model my application after the Basket service and the error seems to be coming from redis. Apparently Autofac is having difficulty instantiating redis.

`'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Corper.Infrastructure.Repositories.StatusRepository' can be invoked with the available services and parameters:\r\nCannot resolve parameter 'StackExchange.Redis.ConnectionMultiplexer redis' of constructor 'Void .ctor(Corper.Infrastructure.CorperContext, Microsoft.Extensions.Logging.ILoggerFactory, StackExchange.Redis.ConnectionMultiplexer)'. (See inner exception for details.)`

StatusRepository class:
```
public class StatusRepository : IStatusRepository
    {
        private readonly ILogger<StatusRepository> _logger;
        private readonly ConnectionMultiplexer _redis;
        private readonly IDatabase _database;
        private readonly CorperContext _context;

        public IUnitOfWork UnitOfWork
        {
            get
            {
                return _context;
            }
        }

        public StatusRepository(CorperContext context, ILoggerFactory loggerFactory, ConnectionMultiplexer redis)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = loggerFactory.CreateLogger<StatusRepository>();
            _redis = redis;
            _database = redis.GetDatabase();
        }

        public Status Add(Status status)
        {

            if (status.IsTransient())
            {
                return _context.Statuses
                    .Add(status)
                    .Entity;
            }
            else
            {
                return status;
            }
        }
```
same as the basket repository class for eShopOnContainers:
https://github.com/dotnet-architecture/eShopOnContainers/blob/93727c259c51e9690c88bf47b1fcbf0daffe9c14/src/Services/Basket/Basket.API/Infrastructure/Repositories/RedisBasketRepository.cs#L11

The basket service application goes on to register the repository using:
https://github.com/dotnet-architecture/eShopOnContainers/blob/93727c259c51e9690c88bf47b1fcbf0daffe9c14/src/Services/Basket/Basket.API/Startup.cs#L171

Now the comment in the startup.cs class where a connection to redis is established says the application should fail to run if redis isn't running. I did a `dotnet run` but the basketapi runs just fine even though redis isnt running on my machine!!
https://github.com/dotnet-architecture/eShopOnContainers/blob/93727c259c51e9690c88bf47b1fcbf0daffe9c14/src/Services/Basket/Basket.API/Startup.cs#L72
```
//By connecting here we are making sure that our service
            //cannot start until redis is ready. This might slow down startup,
            //but given that there is a delay on resolving the ip address
            //and then creating the connection it seems reasonable to move
            //that cost to startup instead of having the first request pay the
            //penalty.
            services.AddSingleton<ConnectionMultiplexer>(sp =>
            {
                var settings = sp.GetRequiredService<IOptions<BasketSettings>>().Value;
                var configuration = ConfigurationOptions.Parse(settings.ConnectionString, true);

                configuration.ResolveDns = true;

                return ConnectionMultiplexer.Connect(configuration);
            });
```

Again, i reiterate  the fact that i'm trying to run the application outside docker using visual studio, would you mind pointing out where i got it wrong. for academic purposes i'd like to know what's happening under the hood :) .

**Comment by mvelosop** [comment]
Hi @FrankDupree,

If I understood you right, you are running eShopOnContainers by executing all required apps right from VS, is that it?

If that's the case, the app should run, although I haven't tried that way.

However, I know you'll have to fix some configurations in appsettings, because there at least some of them that are not in sync with the code.

Right now, since the microservices and apps run from containers, configuration is **mostly** taken from **docker-compose.override.yml**, so you'd have to check that all configuration variables currently in docker-compose.override.yml are also in the corresponding appsettings.json.

Also, when you find a url like `PurchaseUrl=http://webshoppingapigw` you have to configure it in appsettings.json with the local address, that you can also find in docker-compose.override.yml:

```yml
  webshoppingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - CatalogUrlHC=http://catalog.api/hc
      - OrderingUrlHC=http://ordering.api/hc
      - IdentityUrlHC=http://identity.api/hc             
      - BasketUrlHC=http://basket.api/hc
      - MarketingUrlHC=http://marketing.api/hc
      - PaymentUrlHC=http://payment.api/hc
      - LocationUrlHC=http://locations.api/hc
    ports:
      - "5202:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Shopping/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}
```
So in this case you'd have con configure:
```json
"PurchaseUrl": "http://localhost:5202"
```

However, as I write this I realize that there's a "trick" with the API gateways that works great in containers, but probably don't when running locally from VS.

Will elaborate later if this is the situation.

Hope this helps.
