### ISSUE TITLE
Login workflow does not work from mvc app to identity.api

### ISSUE THREAD

**Issue by raimundoteixeira** [dotnet-architecture/eShopOnContainers#1050]
i'm experiencing some network weird issues... when I try to make a login, through the docker network 10.0.75.1:5105, the initial process seems to works fine (it doesnt work if forced by "localhost" or the container's name).  checking the log, it finds the client id but an exception occurs when it tries to check the returnUrl. An exception is thrown by "AuthorizeRequestValidator".

LOG --------
IdentityServer4.EntityFramework.Stores.ClientStore:Debug: **mvc found in database: True**
[41m[30mfail[39m[22m[49m: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      **Invalid redirect_uri: http://localhost:5100/signin-oidc**
END LOG -----------

It seems like when running into local dev-machine, the MVC app with address localhost:5100 can access the Identity.api by 10.0.75.1:5105 but when it try to proceed checking within AuthorizeRequestValidator it cannot reach the returnURL http://localhost:5100/signin-oidc produced during this process... seems like the container network cannot access this address
I already freed all ports in firewall as well as disabled the firewall...

**Comment by mvelosop** [comment]
Hi @raimundoteixeira,

Pleas take a look at this comment: https://github.com/dotnet-architecture/eShopOnContainers/issues/686#issuecomment-410226422

You can connect to the containerized SQL Server this way:

![image](https://user-images.githubusercontent.com/7357806/58173169-8fbb5880-7c92-11e9-91b6-23b3c94429dd.png)

Where:
- Server name: `localhost,5433`
- Login: `sa`
- Password: `Pass@word`

BTW, you can also look at the logs in http://localhost:5340

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment. Will reopen if needed.

**Comment by raimundoteixeira** [comment]
Hi @mvelosop thank you for your collaboration. But my problem has nothing to do with database access. It is working fine. As I said before, I cannot access the mvc client url from within the identity.api (when i try to proceed with the login). 

In the comment you mentioned (#686) @eiximenis explains how mvc client tries to access the identity.api.  
well... when i run export command in the mvc client the identityUrl is http://10.0.75.1:5105 (and this one works fine).
when i type export command in the identity.api the mvc client url is "http://:5100" (and all others clients like WebhooksWebClient = "http://:5114", BasketApiClient = "http://:5103", etc)

and when I execute the command "curl http://localhost:5100" inside Identity.Api it gives me a **"CONNECTION REFUSED"** response.
despite the comment in .env file (#Local: You need to open your local dev-machine firewall at range 5100-5110.) I did this twice. but it is not working...  and it seems like trying to access localhost:5100 inside identity.api it is trying to access its own container (identity.api on port 5100)...  

So I really appreciate if you guys could help me to make it works. maybe a docker configuration is missing or something like that...

**Comment by raimundoteixeira** [comment]
Hi  @mvelosop could you please reopen this post? thanks

**Comment by mvelosop** [comment]
Hi @raimundoteixeira, 

The linked comment wasn't really about DB connections, but about the data in the ClientRedirectUris table.

Those addresses are the identity server callback address whitelist for logging in, so that's what blocks the connection depending on the initial URL.

So, as stated in the comment, the solution can be:

1. Connect to Identity DB and update the values or
2. Drop the Identity DB, update appsettings.json and restart Identity.api container.

This would be the records to update:
![image](https://user-images.githubusercontent.com/7357806/43640769-15b1d4f6-9719-11e8-97d3-5056296c5996.png)

Hope this helps.

**Comment by raimundoteixeira** [comment]
Thanks @mvelosop. I've checked that table (ClientRedirectUris) before. My problem is when the Identity.Api Container tries to access http://localhost:5100 it gets a "connection refused" message. My firewall is disabled...

**Comment by mvelosop** [comment]
Ok @raimundoteixeira, let's try this:

The client urls for identity.api are take from the `docker-compose.override.yml` lines:

```yml
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - XamarinCallback=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback      #localhost do not work for UWP login, so we have to use "external" IP always
      - ConnectionString=${ESHOP_AZURE_IDENTITY_DB:-Server=sql.data;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word} 
      - MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5100              #Local: You need to open your local dev-machine firewall at range 5100-5110. 
      - LocationApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5109
      - MarketingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110
      - BasketApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - MobileShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121
      - WebhooksApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5113
      - WebhooksWebClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5114
      - UseCustomizationData=True  
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5105:80"   
```

and the `ESHOP_EXTERNAL_DNS_NAME_OR_IP` variable is taken from the `.env` file, that should have these value:

```env
ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
```

It'd be good to check the logs, if you go to http://10.0.75.1:5340 you should be able to get something like this response from identity.api upon a successful login:

![image](https://user-images.githubusercontent.com/7357806/58436705-a3b1f080-80be-11e9-87f8-abfe0ca98aee.png)

Hope this helps.
