### ISSUE TITLE
Need Help: Unable to access RabbitMQ Management Portal

### ISSUE THREAD

**Issue by ejstan** [dotnet-architecture/eShopOnContainers#1091]
Hi,

I'm a newbie in AKS and currently studying this architecture. I am trying to figure out why I can't access the RabbitMQ management portal. I already added the following:

- docker-compose.yml

```
version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
```

- docker-compose.prod.yml
```
version: '3.4'

services:

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port
```

![image](https://user-images.githubusercontent.com/41017609/60885085-42666b00-a281-11e9-8eab-f230340ef4ab.png)

Can you please help me and tell me what I'm doing wrong?
