### ISSUE TITLE
How to customize or change base router Authorize?

### ISSUE THREAD

**Issue by phamminhphuc** [dotnet-architecture/eShopOnContainers#1182]
Hi Leader,
I've one question,how to customize base router of Authorize at web SPA,i already change or add new in Authorize function but when run don't change or effect in browser.
![Capture](https://user-images.githubusercontent.com/19634383/69967496-1a86e500-154b-11ea-85ae-16ee5653c50b.PNG)

Thanks, Best Regard!

**Comment by sughosneo** [comment]
Hi @phamminhphuc, thanks for reaching out.

I am not sure if I understood your question right. But still I would try answer like this. Please feel free to comment back if it intended to be something different.

This `this.authorityUrl = this._configurationService.serverSettings.identityUrl` is getting set by the following environment variable section in `docker-compose.override.yml` file.

```yml
 webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
```

If you want to use any different identity url as authorization provider that needs to be passed as environment variable while bringing up the dockers for different component.
