### ISSUE TITLE
[QUESTION] Azure Pipelines - DockerHub | What must I change?

### ISSUE THREAD

**Issue by dervistalha** [dotnet-architecture/eShopOnContainers#1430]
Hello;
I would like to push docker images to another repo by using Azure Build Pipelines. The application attempts to push images to eshop repo but I couldn't have configured to push images to another repo.

multiarch manifests step gives the following error messages:

```
/build/azure-devops/multiarch.yaml
  ...
  registry: 'eshop'
  registryEndpoint: 'dervistalha'
  ...

Created manifest list docker.io/eshop/catalog.api:dev
Created manifest list docker.io/eshop/catalog.api:latest
failed to put manifest docker.io/eshop/catalog.api:dev: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

failed to put manifest docker.io/eshop/catalog.api:latest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

##[error]Bash exited with code '1'.
Finishing: Create multiarch manifest
```

```
/build/azure-devops/multiarch.yaml
  ...
  registryEndpoint: 'dervistalha'
  registryEndpoint: 'eshop'
  ...
Created manifest list docker.io/***/catalog.api:dev
no such manifest: docker.io/***/catalog.api:linux-latest
sha256:73a1c0c5001fe193567c1fa99bf20e00c570651b8dc0f7763ade1444901234f6
No such manifest: docker.io/***/catalog.api:latest

##[error]Bash exited with code '1'.
Finishing: Create multiarch manifest

```

```
/build/azure-devops/multiarch.yaml
  ...
  registry: 'dervistalha'
  registryEndpoint: 'dervistalha'
  ...
Created manifest list docker.io/***/catalog.api:dev
no such manifest: docker.io/***/catalog.api:linux-latest
sha256:8a6f414aa03ebf3efed77337df65c31363caf5f4d1a5bb5ac6a882c11909f383
No such manifest: docker.io/***/catalog.api:latest

##[error]Bash exited with code '1'.
Finishing: Create multiarch manifest
```

```
/build/azure-devops/multiarch.yaml
  ...
  registryEndpoint: 'eshop-registry'
  registryEndpoint: 'dervistalha'
  ...
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

errors:
denied: requested access to the resource is denied
unauthorized: authentication required

No such manifest: docker.io/eshop-registry/catalog.api:dev
No such manifest: docker.io/eshop-registry/catalog.api:latest

##[error]Bash exited with code '1'.
Finishing: Create multiarch manifest

```

```
/build/azure-devops/multiarch.yaml
  ...
  registry: 'eshop'
  registryEndpoint: 'eshot-registry'
  ...
Created manifest list docker.io/eshop/catalog.api:dev
Created manifest list docker.io/eshop/catalog.api:latest
failed to put manifest docker.io/eshop/catalog.api:dev: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

failed to put manifest docker.io/eshop/catalog.api:latest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required


##[error]Bash exited with code '1'.
Finishing: Create multiarch manifest

```

What must I change?

**Comment by sughosneo** [comment]
Hello @dervistalha, thank you for reaching out. 

We have this wiki page [Azure DevOps](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Azure-DevOps-pipelines) which talks about using existing pipeline yaml. Along with that you need to make sure of the following :

1) Creating a service connection of Docker Registry / Azure Container Registry - whichever you are planning to use. 

https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-using-automated-security

2) Then you need to make sure you are passing the `REGISTRY` name to `docker-compose` build and push steps. It's needed because in `docker-compose.yaml`, `eshop` is the default value. Better to define a variable and use that value but for simplicity below example can be referred.

```yaml

- job: BuildLinux
  condition: ne('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DockerCompose@0
    displayName: Compose build ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'build ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=sughosneo
  - task: DockerCompose@0
    displayName: Compose push ${{ parameters.images }}
    inputs:
      dockerComposeCommand: 'push ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=sughosneo
  - task: CopyFiles@2
    inputs:
      sourceFolder: ${{ parameters.helmfrom }}
      targetFolder: ${{ parameters.helmto }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ${{ parameters.helmto }}
      artifactName: helm

```
> !IMPORTANT Please note you can modify/override the value of individual configuration based on your choice. You can also tweak the condition of triggering the pipeline.

Once the job runs successfully, you should be able to see the latest image is pushed to the repository.

Hope this helps !
