### ISSUE TITLE
[BUG?] Azure Pipelines

### ISSUE THREAD

**Issue by dervistalha** [dotnet-architecture/eShopOnContainers#1432]
build/azure-devops/buildimages.yaml doesn't create/push docker images which have "latest" tag.

I don't know why it's needed to docker manifest create/push things/steps in "build/azure-devops/multiarch.yaml" but build/azure-devops/multiarch.yaml attempts to access docker images which have :latest tag. As there are no ":latest" images in DockerHub, the pipeline fails.

**Comment by sughosneo** [comment]
Hi @dervistalha, `multiarch.yaml` is present to build the docker context for multiple platforms. So that you don't need to use win-dev or linux-dev, the tag dev will pick the right architecture automatically. 

Also, yes. ":latest" tag is available under `eshop` repository in docker hub. Please find below screenshot for your reference :

![image](https://user-images.githubusercontent.com/13281246/93351388-50d1ee80-f857-11ea-84c7-ad0c5280af3e.png)

You can use any of these tags to pull the latest docker image in your local.

Hope this helps !

Thank you.

**Comment by dervistalha** [comment]
Thanks for your attention and answer @sughosneo .
I was misunderstood.
Yes, there are :lates tagged images in eshop registry but the problem :latest images cannot be created/pushed to my own repo when I do following modifications here https://github.com/dotnet-architecture/eShopOnContainers/issues/1430#issuecomment-693689058. That's why multiarch.yml fails in "push" step.

![image](https://user-images.githubusercontent.com/71238946/93397509-6c062380-f882-11ea-8809-2013425ba4a1.png)

**Comment by sughosneo** [comment]
Hello @dervistalha, thanks for the update. 

You should be able to push the `latest` tag. And the images which you have build and pushed into your container registry, you should also be able to create the manifest for them.  You may want to review the following aspects :

1) Available docker tags which you have build and pushed into your container registry. 
2) If there is any modification in `buildimages.yml` and `azure-pipelines.yml` which hasn't tagged the right images.

Hope this helps !

**Comment by dervistalha** [comment]
sorry, I didn't understand what you meant.

1# I believe so but that's the problem.

2# I didn't change `azure-pipelines.yml` and `buildimages.yml` files. 
I only changed docker-compose.yml; replaced `${REGISTRY:-eshop}` with `${REGISTRY:-dervistalha}`.

Where/which step are images tagged in code as `latest`?

**Comment by sughosneo** [comment]
> sorry, I didn't understand what you meant.
> 
> 1# I believe so but that's the problem.
> 
> 2# I didn't change `azure-pipelines.yml` and `buildimages.yml` files.
> I only changed docker-compose.yml; replaced `${REGISTRY:-eshop}` with `${REGISTRY:-dervistalha}`.
> 
> Where/which step are images tagged in code as `latest`?

I meant you should be able to push the `latest` tag to dockerhub. For e.g :

![image](https://user-images.githubusercontent.com/13281246/93562287-5dfbf400-f9a3-11ea-8718-5371227ae6e4.png)


Actually `latest` tag gets generated by default. It means the last successful build of your docker image.
More over you don't need to change anything in `docker-compose.yaml` file. You can pass the custom registry value through `buildimages.yaml`. For e.g :

```powershell
dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=sughosneo
```

To perform a quick test, I was able to create one of the pipeline of `WebMVC` app and able to push the images to my dockerhub. I am using following yaml files. 

**azure-pipeline.yaml**
```yaml

variables:
    registryEndpoint: sughosneo-registry
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Web/WebMVC/*
    - build/azure-devops/buildimages.yml
    - build/azure-devops/multiarch.yml
    - build/azure-devops/webmvc/*
    - deploy/k8s/helm/webmvc/*
jobs:
- template: ../buildimages.yaml
  parameters:
    services: webmvc
    registryEndpoint: $(registryEndpoint)
    helmfrom: $(Build.SourcesDirectory)/deploy/k8s/helm
    helmto: $(Build.ArtifactStagingDirectory)/deploy/k8s/helm
- template: ../multiarch.yaml
  parameters:
    image: webmvc
    branch: $(Build.SourceBranchName)
    registry: sughosneo
    registryEndpoint: $(registryEndpoint)

```

**buildimages.yaml**


```yaml
parameters:
  services: ''
  registryEndpoint: ''
  helmfrom: ''
  helmto: ''

jobs:
- job: BuildContainersForPR_Linux
  condition: eq('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: docker-compose -f src/docker-compose.yml build ${{ parameters.services }}
    displayName: Compose build ${{ parameters.services }}
    env:
      TAG: ${{ variables['Build.SourceBranchName'] }}
- job: BuildContainersForPR_Windows
  condition: False
  # condition: eq('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: docker-compose f src/docker-compose.yml build ${{ parameters.services }}
    displayName: Compose build ${{ parameters.services }}
    env:
      TAG: ${{ variables['Build.SourceBranchName'] }}
      PLATFORM: win
      NODE_IMAGE: stefanscherer/node-windows:10
- job: BuildLinux
  condition: ne('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DockerCompose@0
    displayName: Compose build ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'build ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=sughosneo
  - task: DockerCompose@0
    displayName: Compose push ${{ parameters.images }}
    inputs:
      dockerComposeCommand: 'push ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=sughosneo
  - task: CopyFiles@2
    inputs:
      sourceFolder: ${{ parameters.helmfrom }}
      targetFolder: ${{ parameters.helmto }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ${{ parameters.helmto }}
      artifactName: helm
- job: BuildWindows
  condition: False
  # condition: ne('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DockerCompose@0
    displayName: Compose build ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'build ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        PLATFORM=win
        NODE_IMAGE=stefanscherer/node-windows:10
  - task: DockerCompose@0
    displayName: Compose push ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'push ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        PLATFORM=win
```

**multiarch.yaml**

```yaml

parameters:
  image: ''
  branch: ''
  registry: 'sughosneo'
  registryEndpoint: ''

jobs:
- job: manifest
  condition: and(succeeded(),ne('${{ variables['Build.Reason'] }}', 'PullRequest'))
  dependsOn:
    # - BuildWindows
    - BuildLinux  
  pool: 
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Docker@1
    displayName: Docker Login
    inputs:
      command: login
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      # Disabled windows deploy
      # docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:${{ parameters.branch }} ${{ parameters.registry }}/${{ parameters.image }}:linux-${{ parameters.branch }} ${{ parameters.registry }}/${{ parameters.image }}:win-${{ parameters.branch }}
      # docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:latest ${{ parameters.registry }}/${{ parameters.image }}:linux-latest ${{ parameters.registry }}/${{ parameters.image }}:win-latest
  - bash: |
      mkdir -p ~/.docker
      sed '$ s/.$//' $DOCKER_CONFIG/config.json > ~/.docker/config.json
      echo ',"experimental": "enabled" }' >> ~/.docker/config.json
      docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:${{ parameters.branch }} ${{ parameters.registry }}/${{ parameters.image }}:linux-${{ parameters.branch }}
      docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:latest ${{ parameters.registry }}/${{ parameters.image }}:linux-latest
      docker --config ~/.docker manifest push ${{ parameters.registry }}/${{ parameters.image }}:${{ parameters.branch }}
      docker --config ~/.docker manifest push ${{ parameters.registry }}/${{ parameters.image }}:latest
    displayName: Create multiarch manifest

```

Hope this helps !

Thank you.

**Comment by dervistalha** [comment]
@sughosneo I'm sorry to tell that but there is still something missing. Maybe I do something wrong; I don't know. I did whatever you adviced:

**multiarch.yml**
```
parameters:
  image: ''
  branch: ''
  registry: 'dervistalha'
  registryEndpoint: ''

jobs:
- job: manifest
  condition: and(succeeded(),ne('${{ variables['Build.Reason'] }}', 'PullRequest'))
  dependsOn:
    # - BuildWindows
    - BuildLinux  
  pool: 
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Docker@1
    displayName: Docker Login
    inputs:
      command: login
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      # Disabled windows deploy
      # docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:${{ parameters.branch }} ${{ parameters.registry }}/${{ parameters.image }}:linux-${{ parameters.branch }} ${{ parameters.registry }}/${{ parameters.image }}:win-${{ parameters.branch }}
      # docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:latest ${{ parameters.registry }}/${{ parameters.image }}:linux-latest ${{ parameters.registry }}/${{ parameters.image }}:win-latest
  - bash: |
      mkdir -p ~/.docker
      sed '$ s/.$//' $DOCKER_CONFIG/config.json > ~/.docker/config.json
      echo ',"experimental": "enabled" }' >> ~/.docker/config.json
      docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:${{ parameters.branch }} ${{ parameters.registry }}/${{ parameters.image }}:linux-${{ parameters.branch }}
      docker --config ~/.docker manifest create ${{ parameters.registry }}/${{ parameters.image }}:latest ${{ parameters.registry }}/${{ parameters.image }}:linux-latest
      docker --config ~/.docker manifest push ${{ parameters.registry }}/${{ parameters.image }}:${{ parameters.branch }}
      docker --config ~/.docker manifest push ${{ parameters.registry }}/${{ parameters.image }}:latest
    displayName: Create multiarch manifest
```
**buildimages.yml**

```
parameters:
  services: ''
  registryEndpoint: ''
  helmfrom: ''
  helmto: ''

jobs:
- job: BuildContainersForPR_Linux
  condition: eq('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: docker-compose -f src/docker-compose.yml build ${{ parameters.services }}
    displayName: Compose build ${{ parameters.services }}
    env:
      TAG: ${{ variables['Build.SourceBranchName'] }}
- job: BuildContainersForPR_Windows
  condition: False
  # condition: eq('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: docker-compose f src/docker-compose.yml build ${{ parameters.services }}
    displayName: Compose build ${{ parameters.services }}
    env:
      TAG: ${{ variables['Build.SourceBranchName'] }}
      PLATFORM: win
      NODE_IMAGE: stefanscherer/node-windows:10
- job: BuildLinux
  condition: ne('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DockerCompose@0
    displayName: Compose build ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'build ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=dervistalha
  - task: DockerCompose@0
    displayName: Compose push ${{ parameters.images }}
    inputs:
      dockerComposeCommand: 'push ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        REGISTRY=dervistalha
  - task: CopyFiles@2
    inputs:
      sourceFolder: ${{ parameters.helmfrom }}
      targetFolder: ${{ parameters.helmto }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ${{ parameters.helmto }}
      artifactName: helm
- job: BuildWindows
  condition: False
  # condition: ne('${{ variables['Build.Reason'] }}', 'PullRequest')
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DockerCompose@0
    displayName: Compose build ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'build ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        PLATFORM=win
        NODE_IMAGE=stefanscherer/node-windows:10
  - task: DockerCompose@0
    displayName: Compose push ${{ parameters.services }}
    inputs:
      dockerComposeCommand: 'push ${{ parameters.services }}'
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ variables['Build.SourceBranchName'] }}
        PLATFORM=win
```
**azure-pipelines.yml**

```
variables:
    registryEndpoint: dervistalha-registry
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Services/Basket/*
    - build/azure-devops/buildimages.yml
    - build/azure-devops/multiarch.yml
    - build/azure-devops/basket-api/*
    - deploy/k8s/helm/basket-api/*
jobs:
- template: ../buildimages.yaml
  parameters:
    services: basket-api
    registryEndpoint: $(registryEndpoint)
    helmfrom: $(Build.SourcesDirectory)/deploy/k8s/helm
    helmto: $(Build.ArtifactStagingDirectory)/deploy/k8s/helm
- template: ../multiarch.yaml
  parameters:
    image: basket.api
    branch: $(Build.SourceBranchName)
    registry: dervistalha
    registryEndpoint: $(registryEndpoint)

```

![image](https://user-images.githubusercontent.com/71238946/93658266-d2d23b00-fa42-11ea-87f4-5381b3b77ab0.png)
