### ISSUE TITLE
Test results owned by root after running unit tests on self-hosted Azure DevOps Agent

### ISSUE THREAD

**Issue by eifinger** [dotnet-architecture/eShopOnContainers#1433]
Hi,
thank you for publishing and maintaining this project. It is a great reference for many aspects of developing in the .NET ecosystem.

For a professionell project developed by a small team of <10 People we followed the ci/build structure of this repo. We are using AzureDevOps with self hosted Agents and run our Unit Tests in docker containers following the Dockerfiles and [docker-compose-test.yml](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose-tests.yml) approach showed in this repo.

After a run `.trx` files are located in the `BUILD_ARTIFACTSTAGINGDIRECTORY`. The problem is, that these files were created inside the container and are thus owned by `root:root`. The agent process is not running as root because this is a shared server and might lead to (security) issues. This means the agent can never remove those files.

Do you have an idea how to solve that problem?

---

What I tried so far:

Instead of the entrypoint:

`dotnet test --logger trx --results-directory /test-results` 

the following entrypoint is used which changes the file permissions after the dotnet test command:

`"/bin/sh", "-c", "dotnet test --logger trx --results-directory /test-results; success=$?; chmod -R 777 /test-results/*; exit $success"`

The problem with this is that the chmod command might not be executed when the build is cancelled. This happens for example because the build was running longer than the standard 60 minutes.

**Comment by sughosneo** [comment]
Hello @eifinger, thank you for your valuable feedback. 

To my opinion, you can try to publish the test result as a report through the Azure DevOps pipeline. 
Yes, those files get created inside the container but it can be resued and once the containers get destroyed the file gets deleted as well.

Here is the detailed documentation on [Publish Test Results task](https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml).

Hope this helps !

**Comment by eifinger** [comment]
Hi. No the files are not located in the container. They are located on the host system because a volume got mapped to the container.

I can successfully upload and work with the files. I cannot get rid of them^^

**Comment by sughosneo** [comment]
@eifinger - thanks for the update. 

The possible reason for which you might not able to delete the file in the host is because of running process within the container is keeping a lock on the generated file in the host.
How about you generate the test report file, make a copy of it for future use and then delete it ? For e.g : [Define the build pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#define-the-build-pipeline)

To my opinion, [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html) might be a good forum for this question. You can post your question there to fetch further help !

**Comment by eifinger** [comment]
I solved the issue by using the docker cp command to get the files out of the container instead of using a mount. The files copied over are automatically owned by the user which executed the command.

I changed the docker-compose files like the following example:

```yaml
basket-api-functional-test:
    image: ${REGISTRY:-eshop}/basket-api-test:${TAG:-latest}
    container_name: ${CONTAINER_NAME:-basket-api-functional-test}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      target: functionaltest
    depends_on:
      - basket-data-test
      - identity-api-test
      - rabbitmq-test
```

And the azure-pipelines snippet looks like the following:

```yaml
  - task: DockerCompose@0
    displayName: 'Build and Test basket-api-functional-test'
    inputs:
      action: Run services
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: ${{ parameters.dockerRegistryEndpoint }}
      dockerComposeFile: ${{ parameters.dockerComposeFileBasePath }}/docker-compose-tests.yaml
      dockerComposeFileArgs: |
        CONTAINER_NAME=basket-api-functional-test
      qualifyImageNames: false
      projectName: ${{ parameters.projectName }}
      buildImages: true
      detached: false
      abortOnContainerExit: true
  - task: CmdLine@2
    displayName: 'Copy Test and Codecoverage Results'
    inputs:
      script: "docker cp basket-api-functional-test:/test-results/. $(Common.TestResultsDirectory)"
```
