### ISSUE TITLE
Unable to convert YAML as JSON

### ISSUE THREAD

**Issue by JBWereRuss** [dotnet-architecture/eShopOnContainers#1534]
I'm having a problem getting the Envoy api gateways to run, they exit with the message:

```
> docker-compose up webshoppingapigw

webshoppingapigw_1          | [2020-12-03 20:53:25.644][1][critical][main] [source/server/server.cc:93] error initializing configuration '/etc/envoy/envoy.yaml': Unable to convert YAML as JSON:
webshoppingapigw_1          | [2020-12-03 20:53:25.644][1][info][main] [source/server/server.cc:560] exiting
webshoppingapigw_1          | Unable to convert YAML as JSON:
src_webshoppingapigw_1 exited with code 1
```
All the other containers are running fine, but I just can't seem to get these gateways to run. Any help would be much appreciated, thanks.

Docker engine v19.03.13, WSL2, buildkit: true

**Comment by sughosneo** [comment]
Hi @JBWereRuss, thank you for reaching out.

I am unable to reproduce this behavior from `PowerShell`, in one of the environment WSL2 environment with Docker Engine `v19.03.13`, `docker-compose version 1.27.4, build 40524192` and the following configuration

```json
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```
When I looked at the error message over the internet, I could see https://github.com/envoyproxy/envoy/issues/4638. 
Did you try to run the commands from PowerShell ?

**Comment by JBWereRuss** [comment]
Thanks @sughosneo, 

I had a look at that Envoy issue - I changed my config to this got the but same result.

```
version: '3.8'

webshoppingapigw:
    volumes:
    - type: bind
      source: ./ApiGateways/Envoy/config/webshopping
      target: /etc/envoy
    ports:
    - "5202:80"
    - "15202:8001"
```


Fyi, I'm using PowerShell
