### ISSUE TITLE
Call APIGateway from MVC client

### ISSUE THREAD

**Issue by Mahenbisht** [dotnet-architecture/eShopOnContainers#1537]
I followed Eshop repository and created a project similar like Eshop repository.

I have Envoy proxy but no aggregator. I have envoy.yaml in a folder. I am unable to call APIGateway from MVC client. 

I have this configuration in docker-compose for Envoy
  bffwebgateway:
    image: ${DOCKER_REGISTRY-}bffwebgateway:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/Envoy/config/web/Dockerfile

I have this configuration in docker-compose.override for Envoy
bffwebgateway:
    volumes:
      - ./ApiGateways/Envoy/config/web/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
    - "8001:8001"
    - "10000:10000"

URL for Identity API is http://bffwebgateway/i/AccountManagement/CountUsers but when I see container the name of Envoy Proxy is dockercompose1256_bffwebgateway_1. Is this the reason that I am unable to call APIGateway from MVC

**Comment by sughosneo** [comment]
Hi @Mahenbisht, thank you for reaching out. 

Are you getting any error while calling another service through Service Proxy ?

This could happen because of many reasons but you may want to check the following :

- If service proxy/API gateway container itself is up and running.
- If the backend service, is up and running.  
- If you have configured the backend service properly in the `envoy.yaml`

You could always refer [webshopping](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/ApiGateways/Envoy/config/webshopping/envoy.yaml) `Envoy` configuration for more details. 

Hope this helps !

**Comment by Mahenbisht** [comment]
Hi, Thanks for detailed information.

Backend service, is up and running. Service proxy/API gateway container itself is up and running.
I receive this error message when I browse envoy proxy URL.
upstream connect error or disconnect/reset before headers. reset reason: connection failure

What may be the reason for this error?

**Comment by Mahenbisht** [comment]
I have a progress what I discussed on 09-December. I am able to call services using ENVOY with localhost URL(http://localhost:8888/b/api/v1/Baskets/8c76867e-0241-448e-9ea1-2a48ed934668). I am unable to call service APIs inside docker. 

These are the updated settings.

I am using port 8888 for my http listener

name: listener_http
address:
socket_address:
address: 0.0.0.0
port_value: 8888


I am using port 80 for basketcluster

- name: basket_service
    connect_timeout: 2.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: basket_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: basketapi
                port_value: 80


docker-compose has envoy image
bffwebgateway:
image: envoyproxy/envoy:v1.16.0

docker-compose.override has port settings for bffwebgateway
bffwebgateway:
volumes:
- ./ApiGateways/Envoy/config/web/envoy.yaml:/etc/envoy/envoy.yaml
ports:
- "8888:8888"
- "9901:9901"



I noticed ports in my running Service proxy/API gateway container. It shows this information.
ContainerPort 	   HostPort 	Port Type
80 		          10000 		TCP
9901 		   9901 		TCP
10000 				        TCP

**Comment by sughosneo** [comment]
Hi @Mahenbisht, thanks for the update. Glad to hear that, you were able to make the API call. 

But looking at the Envoy configuration, I could see that you are using port `8888` as listeners port. Why wouldn't you configure that as port `80` itself ?  Please note this is an internal port never gets exposed outside of the container, so there won't be any possibilities of colliding with any other service. If you are trying to access the API outside of the docker network then you can use the port `8888` along with DNS (For e.g `webshoppingapigw` http://localhost:5202/ - in `eShop` scenario) but if you are using API from the docker then  you don't need to pass the port number,  you should be able to access the API with the service name itself. For e.g http://bffwebgateway or (PurchaseUrl=http://webshoppingapigw) as shown in the `eShop` app. 

For more details, you can take a look at the configuration of the `webshoppingapigw` service in the `docker-compose.override.yml` file and how it's getting referred as an environment variable (PurchaseUrl) in the `webmvc`

Hope this helps !

**Comment by Mahenbisht** [comment]
Hi, Thanks for reply.

I did follow the eshop repository. 
Yes, webshoppingagg is configured on port 80 but webshoppingapigw is not configured on 80.
It has only Admin and https configuration. Currently there is no provision to call APIs without any aggregate using http.

Could you please check webshoppingapigw  for http on port 80. Let me know if that works. I tried with all the possible options to configure webshoppingapigw  for http on port 80.  But I did not get success.

**Comment by sughosneo** [comment]
Hi @Mahenbisht, thanks for the update. 

I have created a small solution (envoy-sample.sln) to test out the `Envoy` service proxy related configuration. This solution architecture is as per below :

-----------------               ----------              ----------------
| Weather API 1 |     ---->     | Envoy  |      ---->   | Weather API 2 |
-----------------               ----------              ----------------

> Note: Each component is hosted through the docker container.

Now, in this scenario `Weather API 1` calls the `Weather API 2` to fetch the data through `Envoy` and give it back to the client. 
Below is the `envoy.yaml` and `docker-compose` yamls for your reference. 

<details>
<summary>envoy.yaml </summary>
<p>

```yaml

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: api_backend_route
            virtual_hosts:
            - name: api_backend
              domains:
              - "*"
              routes:              
                match:
                  prefix: "/"
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: weather-api-2   
          http_filters:
          - name: envoy.router
          access_log:
          - name: envoy.file_access_log
            filter:
              not_health_check_filter: {}
            config:
              json_format:
                time: "%START_TIME%"
                protocol: "%PROTOCOL%"
                duration: "%DURATION%"
                request_method: "%REQ(:METHOD)%"
                request_host: "%REQ(HOST)%"
                path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                response_flags: "%RESPONSE_FLAGS%"
                route_name: "%ROUTE_NAME%"
                upstream_host: "%UPSTREAM_HOST%"
                upstream_cluster: "%UPSTREAM_CLUSTER%"
                upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
              path: "/tmp/access.log"
  clusters:
  - name: weather-api-2
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: weather-2
        port_value: 80

```
</p>
</details> 

<details>
<summary>docker-compose.yml</summary>
<p>

```yaml
version: '3.4'

services:
  
  apigw:
    image: envoyproxy/envoy:v1.11.1

  weather-1:
    image: ${DOCKER_REGISTRY-}weather1
    build:
      context: .
      dockerfile: weather-1/Dockerfile

  weather-2:
    image: ${DOCKER_REGISTRY-}weather2
    build:
      context: .
      dockerfile: weather-2/Dockerfile
```
</p>
</details> 

<details>
<summary>docker-compose.override.yml</summary>
<p>

```yaml

version: '3.4'

services:
  
  apigw:
    volumes:
      - ./ApiGateways/Envoy/config/:/etc/envoy
    ports:
    - "5202:80"
    - "15202:8001"

  weather-1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APIGatewayUrl=http://apigw
    ports:
      - "5001:80"

  weather-2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
```
</p>
</details> 


If you notice we are able to configure the `Weather API 2` in `Envoy` filter and able to make the call. 
Please note, all the service call happens through the service name, nothing is hard coded. Yes, everything is listening on port 80 that's the reason I didn't have to mention any specific port number along with the service name. 

Here is the code snippet in `Weather API 1` which is actually making the call to `Weather API 2`. 

<details>
<summary>Code Snippet</summary>
<p>

```C#
public class Weather2Service : IWeather2Service
    {
        private readonly HttpClient _httpClient;
        private readonly string _weather2Url;

        public Weather2Service(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _weather2Url = configuration.GetValue<string>("APIGatewayUrl");
        }

        public async Task<string> GetInformation()
        {
            try
            {
                var responseString = await _httpClient.GetStringAsync(_weather2Url);

                return responseString;
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }

```
</p>
</details> 


`Calling --> Weather API 1`

![image](https://user-images.githubusercontent.com/13281246/102916424-8cf59a80-44a9-11eb-94b8-8e37fe01ad60.png)


Hope this helps !
