### ISSUE TITLE
rabbitmq management console

### ISSUE THREAD

**Issue by robpahl** [dotnet-architecture/eShopOnContainers#246]
Not an Issue, however I need some pointers as how I can enable access to the RabbitMQ management console?
I guess I just have to open the management Port, but as I am somewhat of a rookie here I would appreciate to just get a pointer as how to open this up in the Debug build.

**Comment by MarcinHoppe** [comment]
@robpahl You need to use an image with the management plugin enabled and also expose the default management API port. This is what worked for me (in `docker-compose.yml`):

```
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
```
