### ISSUE TITLE
### Test the SPA web application

### ISSUE THREAD

**Issue by robpahl** [dotnet-architecture/eShopOnContainers#247]
Trying to run the WebSPA however the port (5104) in docker-compose.override does not seem to work.

```
  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5101
      - OrderingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105              #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - BasketUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - MarketingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110
      - CatalogUrlHC=http://catalog.api/hc
      - OrderingUrlHC=http://ordering.api/hc
      - IdentityUrlHC=http://identity.api/hc     #Local: Use ${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}, if using external IP or DNS name from browser.          
      - BasketUrlHC=http://basket.api/hc
      - MarketingUrlHC=http://marketing.api/hc
      - UseCustomizationData=True
    ports:
      **- "5104:80"**

```

and not really clear in the Readme.MD of the WebSPA project. :)

```
### Test the SPA web application

Test the SPA app by running the following URL in a browser:
<b> http://TBD</b>
```
