### ISSUE TITLE
Error deploying Azure web site on Service Fabric (Linux)

### ISSUE THREAD

**Issue by vany0114** [dotnet-architecture/eShopOnContainers#470]
Hey guys,

I've been studying the eShopOnContainers solutions, it's great BTW. So I'm building a little example based on eShopOnContainers examples, but I'm facing a problem deploying and Asp.Net Mvc app or Asp.Net Web Api app on Service Fabric. I've deployed the RabbitMQ, MongoDB and Sql Server images without problems but I haven't able to deploy the website. Even I deployed the eShopOnServiceFabricWebMVC on azure and worked perfectly. So I don't know if is a problem with my image or something else.

This is the docker image: https://hub.docker.com/r/vany0114/webmvc
Also, this is the information about docker and SF files:

- Asp.Net MVC Docker file:

```
FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY *.sln ./
COPY dockerTest/dockerTest.csproj dockerTest/
RUN dotnet restore
COPY . .
WORKDIR /src/dockerTest
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "dockerTest.dll"]

```

- docker-compose.ci.build.yml:

```
version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
      - ./cli-linux:/cli-linux
    working_dir: /src

    command: /bin/bash -c "pushd ./src/dockerTest && popd && pushd /cli-linux && ./build-bits-linux.sh /src"
    #command: /bin/bash -c "dotnet restore ./dockerTest.sln && dotnet publish ./dockerTest.sln -c Release -o ./obj/Docker/publish"

```
- docker-compose.yml

```
version: '3'

services:
  dockertest:
    image: vany0114/webmvc:${TAG:-dev}
    build:
      context: .
      dockerfile: dockerTest/Dockerfile
    depends_on:
      - webapi1
      - webapi2
      - sql.data
      - rabbitmq

  webapi1:
    image: vany0114/webapi1:${TAG:-dev}
    build:
      context: .
      dockerfile: webApi1/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  webapi2:
    image: vany0114/webapi2:${TAG:-dev}
    build:
      context: .
      dockerfile: webApi2/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
```
- ServiceManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="WebMVCPkg"
                 Version="1.0.0"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <!-- This is the name of your ServiceType.
         The UseImplicitHost attribute indicates this is a guest service. -->
    <StatelessServiceType ServiceTypeName="WebMVCType" UseImplicitHost="true" />
  </ServiceTypes>

  <!-- Code package is your service executable. -->
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      <!-- Follow this link for more information about deploying Windows containers to Service Fabric: https://aka.ms/sfguestcontainers -->
      <ContainerHost>
        <ImageName>vany0114/webmvc:latest</ImageName>
      </ContainerHost>
    </EntryPoint>
    <!-- Pass environment variables to your container: -->
    
    <EnvironmentVariables>
        <EnvironmentVariable Name="ASPNETCORE_ENVIRONMENT" Value="Development"/>
        <EnvironmentVariable Name="ASPNETCORE_URLS" Value="http://0.0.0.0:80"/>
        <EnvironmentVariable Name="Webapi1Url" Value="http://webapi1.testonservicefabric:32775"/>
        <EnvironmentVariable Name="EventBusConnection" Value="rabbitmq.testonservicefabricbus"/>
        <EnvironmentVariable Name="ConnectionString" Value="Data Source=sqlserver.testonservicefabricsql,5433;Database=WebSiteDb;User Id=sa;Password=Pass@word"/>
        <EnvironmentVariable Name="ApplicationInsights__InstrumentationKey" Value=""/>
    </EnvironmentVariables>
    
  </CodePackage>

  <!-- Config package is the contents of the Config directoy under PackageRoot that contains an 
       independently-updateable and versioned set of custom configuration settings for your service. -->
  <ConfigPackage Name="Config" Version="1.0.0" />

  <Resources>
    <Endpoints>
      <!-- This endpoint is used by the communication listener to obtain the port on which to 
           listen. Please note that if your service is partitioned, this port is shared with 
           replicas of different partitions that are placed in your code. -->
      <Endpoint Name="WebMVCTypeEndpoint" UriScheme="http" Port="32776" />
    </Endpoints>
  </Resources>
</ServiceManifest>
```

- ApplicationManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest ApplicationTypeName="testOnServiceFabricWebMVCType"
                     ApplicationTypeVersion="1.0.0"
                     xmlns="http://schemas.microsoft.com/2011/01/fabric"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameters>
        <Parameter Name="WebMVC_InstanceCount" DefaultValue="-1" />
        <Parameter Name="InstrumentationKey" DefaultValue="" />
    </Parameters>
    <!-- Import the ServiceManifest from the ServicePackage. The ServiceManifestName and ServiceManifestVersion 
       should match the Name and Version attributes of the ServiceManifest element defined in the 
       ServiceManifest.xml file. -->
    <ServiceManifestImport>
        <ServiceManifestRef ServiceManifestName="WebMVCPkg" ServiceManifestVersion="1.0.0" />
        <ConfigOverrides />
        <EnvironmentOverrides CodePackageRef="Code">
            <EnvironmentVariable Name="ApplicationInsights__InstrumentationKey" Value="[InstrumentationKey]"/>
        </EnvironmentOverrides>
        <Policies>
            <ContainerHostPolicies CodePackageRef="Code">
                <PortBinding ContainerPort="80" EndpointRef="WebMVCTypeEndpoint"/>
            </ContainerHostPolicies>
        </Policies>
    </ServiceManifestImport>
    <DefaultServices>
        <!-- The section below creates instances of service types, when an instance of this 
         application type is created. You can also create one or more instances of service type using the 
         ServiceFabric PowerShell module.
         
         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
        <Service Name="WebMVC" ServiceDnsName="webmvc.testonservicefabric" ServicePackageActivationMode="ExclusiveProcess">
            <StatelessService ServiceTypeName="WebMVCType" InstanceCount="[WebMVC_InstanceCount]">
                <SingletonPartition />
            </StatelessService>
        </Service>
    </DefaultServices>
</ApplicationManifest>
```
- This is the error son Service Fabric:
![sf_error](https://user-images.githubusercontent.com/12032625/35060749-5a4972f4-fb8d-11e7-9bee-758c734a4df5.png)

> **Note: Locally it works perfectly with docker**

I appreciate if you guys can help me with that!

Thanks!
