### ISSUE TITLE
Docker compose fails with "Cannot locate specified Dockerfile" on Docker Edge for Windows

### ISSUE THREAD

**Issue by stanoislav** [dotnet-architecture/eShopOnContainers#640]
Docker Community Edition
Version 18.05.0-ce-win67 (18263)
Channel: Edge
Compose: 1.21.2

The docker-compose fails for all services that need to be built.
e.g. _Cannot locate specified Dockerfile: src\Services\Catalog\Catalog.API\Dockerfile_

It appears that the way docker-compose handles context has changed.

The fix is to change the format from

```yaml
catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      ccontext: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
```
to

```yaml
  catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      context: src/Services/Catalog/Catalog.API/
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
```
